* BW
** Nele
https://www.germanistik.uni-wuppertal.de/en/teilfaecher/neuere-deutsche-literatur/personal/andreas-meier/benn.html
** Ina Seidel BW:
Einblicke im Benn Jb 2003 von Dorit Krusche, die dort gleichzeitig
eine Komplett-Edition ank"undigt.  Bislang (2017) nicht erschienen.
** Frau Jolas
Brief erwähnt in [[file:briefe/porada.org::#po1933-08-24][po1933-08-24]].
** Jolas
Sendung erwähnt in [[file:briefe/porada.org::#po1933-11-21][po1933-11-21]]
** Literarische Gesellschaft Augsburg
Lesung abgeschrieben; s. [[file:briefe/porada.org::#po1933-10-09][po1933-10-09]].
** Diverse gegenbriefe
*** Erwähnt in [[file:briefe/oelze.org::#oe1935-04-07][oe1935-04-07]], 44
** Evola
Sendungen erwähnt in [[file:briefe/oelze.org::#oe1935-05-24]],
file:briefe/oelze.org::#oe1935-05-25,
file:briefe/oelze.org::#oe1935-11-11,
[[file:briefe/oelze.org::#oeb1935-11-12][oeb1935-11-12]], 88f.,
[[file:briefe/oelze.org::#oeb1935-11-15][oeb1935-11-15]], 91.
** Bense
*** 1935-05-20
Erwähnt in file:briefe/oelze.org::#oe1935-06-04.
** Einladung Mittelmeerakademie
file:briefe/oelze.org::#oe1935-08-20.
** Strässer, August
*** 1935-10-27
DLA, im kommentar zu oeb1935-10-10 erwähnt.
In [[#oe1935-12-09][oe1935-12-09]] abermals erwähnt.
** Diverse briefe
*** Erwähnt in [[file:briefe/oelze.org::#oe1935-11-03][oe1935-11-03]], 84; u.a. an Nele.
*** Erwähnt in  [[file:briefe/oelze.org::#oe1936-04-15][oe1936-04-15]], 145.
** Else C. Kraus
*** Erwähnt in [[file:briefe/oelze.org::#oe1936-02-06][oe1936-02-06]].
** Diverse briefe
*** Erwähnt in [[file:briefe/oelze.org::#oe1936-05-26][oe1936-05-26]], 121 u. 122 (s. 158) und kommentar sowie 124.
*** Erwähnt in [[file:briefe/oelze.org::#oe1936-05-28][oe1936-05-28]], 124 (s. 161).
*** [[file:briefe/oelze.org::#oe1944-01-04][1944-01-04]]
** Verlagssachen
*** 1936-08-13 (vor 1936-08-13)
   :PROPERTIES:
   :CUSTOM_ID: ver1936-08-13
   :TRAD: verloren (?)
   :END:      
   In [[#oe1936-08-13]] und [[#oe1936-08-14]] erwähnt.
** Telefonate
** Widmungen, auch die nur erwähnten
*** Jünger in BOe2016, nr.755
** DVA
In [[#bense1934-10-30]].
** Stadt/Gesundheitsamt
Abgelehnte bewerbung: [[#se1934-12-12]].
** Europ. Revue
Erwähnt in [[#bense1935-02-17]].
** Herta Benn
*** an Seyerlen
    1939-03-28, s. 26f.; 1940-06-12, s. 31; 1942-09-04, s. 36f.;
    1944-07-19, s. 42;
** Unbekannt
*** an Seyerlen
    1945-10-01, s. 43 (gez. Benn)
